### PR TITLE
JBIDE-15154 : provide friendlier url for product downloads

### PR DESCRIPTION
**Pull request by fbricon**
Signed-off-by: Fred Bricon fbricon@gmail.com

### CODE REVIEW

**Comment by rafabene** [comment]
This will affect the Download section of this page: http://www.jboss.org/jdf/stack/stacks/ Is it really desired ?

**Comment by fbricon** [comment]
Yeah that's one side effect, but I think it should be ok. I'll let @pmuir decide

**Comment by pmuir** [comment]
Agree that this is better than the access.redhat.com version

**Comment by rafabene** [comment]
Ok. I'll merge. @pmuir One question: Should we remove the download link from stacks page since we don't provide any or we leave it pointing to the urls of this PR ?

**Comment by pmuir** [comment]
On 10 Jul 2013, at 21:49, Rafael Benevides notifications@github.com wrote:

> Ok. I'll merge. @pmuir One question: Should we remove the download link from stacks page since we don't provide any or we leave it pointing to the urls of this PR ?

I think we can leave it.

**Pull request merged**
