### PR TITLE
JDF-870 - provide Karaf for Fuse 7.0.1

### PR DESCRIPTION
**Pull request by apupier**
await Fuse 7.0.1 public release to merge it

### CODE REVIEW

**Comment by apupier** [comment]
@lhein please review

**Comment by lhein** [comment]
that is not fully correct. Will provide an update later today.

**Comment by apupier** [comment]
works fine when using

`-Dorg.jboss.tools.stacks.url_stacks=https://raw.githubusercontent.com/apupier/jboss-stacks/JDF-870-IncludeKarafForFuse7.0.1/stacks.yaml`

image

**Comment by lhein** [comment]
works here too now

**Comment by lhein** [comment]
@robstryker @fbricon can you review / merge please?

**Comment by lhein** [comment]
Thanks Rob!

**Pull request merged**
