### PR TITLE
Adding support for minishift 1.15.1, 1.16.1, 1.17.0

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by robstryker** [comment]
@odockal  Has this been tested?

**Comment by odockal** [comment]
@robstryker I tried it locally on linux only. I am writing some tests just for case.

**Comment by odockal** [comment]
@robstryker Added some basic tests, parsing of yaml file, and checking http status of minishift's urls. Though, those are running locally I guess, or is there any test job? Note that cdk's url are not tested, cause there is need for authentication, right? I do not know how to improve anything else, ideas?

**Comment by robstryker** [comment]
I was just really checking to make sure hte URLs were ok. Seems your test does that. Thanks.

**Pull request merged**
