### PR TITLE
New RF archetype

### PR DESCRIPTION
**Pull request by fbricon**
this PR supercedes the one from Brian https://github.com/jboss-jdf/jdf-stack/pull/3

### CODE REVIEW

**Comment by rafabene** [comment]
The tests failed with: Can't resolve Archetype [org.richfaces.archetypes:richfaces-archetype-kitchensink:4.2.3.Final-1]

I also didn't find this archetype here: https://repository.jboss.org/nexus/content/groups/public/org/richfaces/archetypes/richfaces-archetype-kitchensink/

Was this already released ?

**Comment by fbricon** [comment]
You need to add the nexus staging repo to your settings (see https://github.com/fbricon/jdf-stack/commit/c01f70924b4ea26fd95a870b3dde5b714a203d69) so the staged archetype can be tested.

**Comment by rafabene** [comment]
Ok. I tested with the staging repo and it's ready to merge when the archetype is on public repo. Do you confirm that ? Can you ping me when it is released ?

**Comment by fbricon** [comment]
I'm waiting for JBDS QE team to greenlight the archetype (should be anytime soon). Will ping @bleathem when it's ok, then he'll ping you when the release is done

**Pull request merged**
