### PR TITLE
Add WildFly 10.1.0.Final runtime

### PR DESCRIPTION
**Pull request by jamezp**

### CODE REVIEW

**Comment by robstryker** [comment]
I haven't tested it, but it looks like this should work fine for devstudio's usecase without error.

**Comment by mmalina** [comment]
Update: Rob tested this 3 days ago - see https://issues.jboss.org/browse/JBIDE-23035
Can this be pushed?

**Comment by robstryker** [comment]
Can this be added @jamezp ?

**Comment by jamezp** [comment]
@robstryker I don't have merge access so there's nothing I can do unfortunately.

**Comment by robstryker** [comment]
This has been merged after a rebase.

**Pull request closed without merging**
