### PR TITLE
Update stacks.yaml with latest RF KS release

### PR DESCRIPTION
**Pull request by bleathem**
RichFaces kitchensink archetype 4.2.3.Final-1 is currently in a JBoss staging repository.

### CODE REVIEW

**Comment by fbricon** [comment]
@jdf-gatekeeper : Before merging, please note the stacks.yml need to be tested by QA ( https://issues.jboss.org/browse/JBIDE-13059), approved, then the repo coordinates should be changed once the archetype is out of staging.

**Comment by fbricon** [comment]
The PR is incomplete. You need to add a new archetype reference like 

```
- &richfaces-archetype-kitchensink-423final1
 id: richfaces-archetype-kitchensink-423final1
 archetype: *richfaces-archetype-kitchensink
 version: 4.2.3.Final-1
 repositoryURL: <<< ADD YOUR STAGING REPO HERE 
 labels: {}
```

And that reference needs to be added to the different runtime declarations in the file

**Comment by rafabene** [comment]
This lines should also be updated https://github.com/bleathem/jdf-stack/blob/a4d996b89e5a311759c2f8c9445cfc75a70cc49f/stacks.yaml#L533-L538

**Comment by rafabene** [comment]
Note that stacks.yaml has its unit tests (recently added). You can run it by doing a mvn test

**Comment by bleathem** [comment]
I've re-based my patch against the master branch, and completed my changes to the stacks.yaml file.  I ran the maven test, and it fails for a test that seems unrelated to the change I made.

Please let me know if there are any additional changes I need to do.

**Comment by rafabene** [comment]
Will handle on pull request #7

**Pull request closed without merging**
