### PR TITLE
Introduce WildFly 26 server runtime

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@jeffmaury take a look please.

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Parts are missing. See e5445715892e83a8ecd61e7192dc3d7efb5f294e

**Comment by odockal** [comment]
@jeffmaury done.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
