### PR TITLE
JDF-733 - Remove DEV BOMs and Archetypes out of Stacks.yaml

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by LightGuard** [comment]
When do we want to do this? We'll have make sure to remove them out of the DCP, and no longer having them mid way through a release (EAP 6, WFK) may be a difficult pill for some to swallow. This will probably affect the jboss.org site as well (list deprecated boms / archetypes at the minimum).

**Comment by rafabene** [comment]
They're not deprecated. They were "just" DEV Bom's that was not released on any product. All of them was on http://jboss-developer.github.io/temp-maven-repo/ repo only!

**Comment by LightGuard** [comment]
Oh, so we're not changing anything that's already been "released"?

On Mon, Jun 30, 2014 at 2:56 PM, Rafael Benevides notifications@github.com
wrote:

> They're not deprecated. They're "just" DEV Bom's that was not released on
> any product. All of them was on
> http://jboss-developer.github.io/temp-maven-repo/ repo only!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jboss-developer/jboss-stacks/pull/42#issuecomment-47585919
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by rafabene** [comment]
@LightGuard exactly! That's the idea: Keep  only "released" stuff on Stacks. That's what this PR do: Remove DEV stuff out of Stacks

**Comment by LightGuard** [comment]
okay, cool. No problems from me then.

On Tue, Jul 1, 2014 at 10:27 AM, Rafael Benevides notifications@github.com
wrote:

> @LightGuard https://github.com/LightGuard exactly! That's the idea:
> Keep only "released" stuff on Stacks. That's what this PR do: Remove DEV
> stuff out of Stacks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jboss-developer/jboss-stacks/pull/42#issuecomment-47678204
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by rafabene** [comment]
@maxandersen and @fbricon Can I merge it ?

**Comment by fbricon** [comment]
I will test it against JBDS tomorrow morning to see if nothing breaks

**Comment by rafabene** [comment]
Thanks @fbricon and @LightGuard

**Comment by fbricon** [comment]
+1 to apply

**Comment by maxandersen** [comment]
+1 to apply this. keep stacks.yml slim and clean. if a "dev" stacks.yml is needed that should be a separate stacks.yml IMO.

**Comment by rafabene** [comment]
PR rebased: https://github.com/jboss-developer/jboss-stacks/commit/cc9daba5e9932e523691ac798311fe343b699c3e

**Pull request closed without merging**
