### PR TITLE
JDF-880 - add Fuse 7.8 release

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
testPR

**Comment by lhein** [comment]
seems the CI has an issue

**Review by jeffmaury — CHANGES_REQUESTED** [review]
There is an indentation issue around line 5379 and - &fuse78

**Comment by lhein** [comment]
good catch. fixed it.

**Comment by jeffmaury** [comment]
testPR

**Comment by lhein** [comment]
thank you @jeffmaury

**Pull request merged**
