### PR TITLE
JDF-683 - runtimes that require subscriptions should still have urls

### PR DESCRIPTION
**Pull request by robstryker**
Adding download urls for the various runtimes that require credentials and subscriptions. This url will analyze the incoming request and determine whether to forward it to the web UI, return an xml response, or simply download the file immediately (if all requirements are met). 

A typical request from a browser will either download the file immediately (if terms and conditions are signed) or redirect to the web ui. 

If the request has a header Accepts: application/xml,   then it will either download the file immediately or return an xml response linking to a rest workflow of what's missing.

### CODE REVIEW

**Comment by rafabene** [comment]
I'm ok with this change since it doesn't break stacks-client. @fbricon. Does this change on downloadURL breaks JBDS ?

**Comment by rafabene** [comment]
I would like to hear the opinion from @fbricon on this.

**Comment by fbricon** [comment]
This will break existing JBDS 7 clients so it's a no-no for the moment.

Either we decide it's ok to break them, or we manage to get a patch in for JBDS 7.1.x., or we decide to duplicate informations somewhere else (new label/new attribute)

**Comment by rafabene** [comment]
Ok. So I'll close this PR for the moment and reject it on Jira.

**Comment by maxandersen** [comment]
Can we reopen this one please ? 7.1.x is out now and will ignore these.

**Comment by robstryker** [comment]
This appears to have already been committed. 
- 58a7c3f - JDF-683 - runtimes that require subscriptions should still have urls (3 months ago, Rob Stryker)|

**Comment by rafabene** [comment]
It was. Closing it...

**Pull request closed without merging**
